### ISSUE TITLE
Hacer que la tarjeta de distribución responda

### ISSUE THREAD

**Issue by teanocrata** [ilice/OSCapi#138]
Ahora mismo simplemente cuando la provincia es Salamanca, se muestra la tarjeta de distribución que toma imágenes fijas y las muestra según la pestaña seleccionada.

Es necesario repensar un poco esto y hacer una tarjeta que aporte información sobre los datos que tenemos. 

Una opción es hacer una tarjeta con el api del maps que pinte las parcelas de alrededor según su uso parcando un zoom máximos y algunos datos sobre lo que estamos viendo.

También podemos ver si se puede meter lo de carto db y se pueden mostrar cosas interesantes en lugar de con el maps.

Es importante ver con qué datos contamos, lo que se ven se cargaban desde sigpac y esa carga no la estamos manteniendo ahora mismo, tenemos datos del catastro que quizá al ir por bbox puedan ser suficientes

**Comment by malgar** [comment]
Tras investigar un poco, parece que tiene sentido seguir usando el api de maps porque para lo que se busca tener, la versión gratis de carto no aportaría nada diferente (la de pago definitivamente sí). 

En mi opinión, una tarjeta con un mapa interactivo en la que se muestren las parcelas dentro de un bbox determinado y se pueda filtrar por clase de cultivo, intensidad de producción o superficie (datos del catastro) puede aportar información interesante para una primera versión. Para bbox grandes, lo podríamos hacer agrupado por municipios. Podría ser interesante acompañarlo de algún gráfico sencillo tipo: diagrama de barras con proporción de parcelas (por número o superficie) por filtro que se haya seleccionado.

@teanocrata , en principio, la idea no dista mucho del mapa que ya me mostraste de Sanchotello con las parcelas dentro de un bbox, por lo que no nos debería costar mucho.

**Comment by teanocrata** [comment]
Issue moved to [ilice/OSCWeb #18](https://github.com/ilice/OSCWeb/issues/18) via [**ZenHub**](https://www.zenhub.com/)
