### ISSUE TITLE
Las parcelas compuestas no se ven como tal en el perfil de la parcela

### ISSUE THREAD

**Issue by teanocrata** [ilice/OSCapi#147]

**Comment by jlafuentegarcia** [comment]
Y esto: ¿a qué se debe? ¿tienes un ejemplo, @teanocrata?

**Comment by jlafuentegarcia** [comment]
Hay un rollo con los inner polygon y los outer polygon, e igual viene por ahí la cosa.

**Comment by teanocrata** [comment]
si, tiene pinta de que puede se por eso, la parcela con la que teníamos prolemas por el tema de la subparcelas, lo del numerito ese que se añadía al final, pues ahora se ve como una sola en todos los casos. En el mapa de parcelas tiene todo el sentido, pero en el perfil debería verse en el mapa cada trocito ya que en la información del catastro se ve (ahora mismo no funciona) la información de cada subparcela.

http://opensmartcountry.com/osc/parcela/?cadastral_code=37284A01600146&nombre=Demo

**Comment by jlafuentegarcia** [comment]
Pues no es eso, no... O al menos no parece. La parcela viene 'con todo'

`This XML file does not appear to have any style information associated with it. The document tree is shown below.

<gml:FeatureCollection xmlns:gml="http://www.opengis.net/gml/3.2" xmlns:gmd="http://www.isotc211.org/2005/gmd" xmlns:ogc="http://www.opengis.net/ogc" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:cp="urn:x-inspire:specification:gmlas:CadastralParcels:3.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" gml:id="ES.SDGC.CP" xsi:schemaLocation="urn:x-inspire:specification:gmlas:CadastralParcels:3.0 http://inspire.ec.europa.eu/schemas/cp/3.0/CadastralParcels.xsd">
<gml:featureMember>
<cp:CadastralParcel gml:id="ES.SDGC.CP.37164A00500001">
<gml:boundedBy>
<gml:Envelope srsName="urn:ogc:def:crs:EPSG::25830">
<gml:lowerCorner>270636.34 4474908.34</gml:lowerCorner>
<gml:upperCorner>271210.83 4475446.2</gml:upperCorner>
</gml:Envelope>
</gml:boundedBy>
<cp:areaValue uom="m2">122818</cp:areaValue>
<cp:beginLifespanVersion>2010-09-28T00:00:00</cp:beginLifespanVersion>
<cp:endLifespanVersion xsi:nil="true" nilReason="other:unpopulated"/>
<cp:geometry>
<gml:MultiSurface gml:id="MultiSurface_ES.SDGC.CP.37164A00500001" srsName="urn:ogc:def:crs:EPSG::25830">
<gml:surfaceMember>
<gml:Surface gml:id="Surface_ES.SDGC.CP.37164A00500001.1" srsName="urn:ogc:def:crs:EPSG::25830">
<gml:patches>
<gml:PolygonPatch>
<gml:exterior>
<gml:LinearRing>
<gml:posList srsDimension="2" count="115">
270636.34 4475408.28 270638.72 4475407.83 270640.55 4475407.48 270656.95 4475410.49 270667.77 4475411.64 270671.42 4475412.02 270690.2 4475414.51 270694.67 4475413.94 270706.76 4475418.94 270717.89 4475422.77 270731.97 4475428.63 270759.05 4475437.91 270784.78 4475441.1 270811.09 4475446.2 270832.4 4475445.22 270869.53 4475442.02 270905.91 4475439.33 270928.08 4475439.21 270938.64 4475439.95 270941.47 4475440.03 270948.27 4475385.06 270947.68 4475384.15 270948.27 4475377.49 270951.6 4475358.62 270955.49 4475338.07 270959.35 4475324.84 270960.53 4475314.21 270964.73 4475296.25 270967.9 4475289.58 270988.93 4475248.45 270991 4475246.71 271001.73 4475238.75 271011.94 4475227.13 271036.48 4475208 271065.9 4475188.5 271081.54 4475176.56 271091.43 4475161.43 271093.89 4475151.88 271115.06 4475069.82 271132.78 4475057.37 271140.77 4475051.75 271160.43 4475029.58 271196.61 4474955.97 271210.83 4474915.62 271143.85 4474916.11 271088.59 4474915.04 271074.75 4474917.72 271065.77 4474918.25 271056.89 4474917.21 271049.28 4474917.63 271040 4474914.56 271038.91 4474914.21 271021.39 4474910.19 271014.54 4474908.37 271007.69 4474908.34 271004.76 4474908.46 271004.68 4474908.53 270999.58 4474913.15 270994.51 4474918.68 270988.92 4474925.98 270983.8 4474933.76 270980.13 4474940.86 270977.39 4474948.9 270974.87 4474959.2 270972.61 4474969.35 270971.77 4474972.52 270965.04 4474984.38 270951.82 4475007.65 270948.08 4475016.18 270936.61 4475042.8 270922.07 4475065.52 270920.02 4475075.33 270918.02 4475082.56 270916.73 4475091.61 270915.49 4475100.61 270914.21 4475110.63 270915.82 4475121 270917.84 4475132.18 270919.5 4475144.58 270921.82 4475154.08 270918.86 4475162.68 270912.79 4475168.14 270903.52 4475172.38 270893.68 4475175.76 270884.56 4475177.92 270876.65 4475181.56 270865.05 4475187.48 270852.49 4475194.28 270845.86 4475198.57 270842.02 4475202.49 270840.19 4475203.31 270829.49 4475206.04 270823.36 4475206.61 270810.72 4475205.73 270800.91 4475205.45 270794.61 4475207.2 270793.66 4475207.46 270787.71 4475208.12 270785.1 4475211.45 270779.47 4475213.04 270767.98 4475219.27 270756.12 4475225.61 270739.99 4475240.3 270734.55 4475253.27 270734.37 4475253.46 270732.85 4475257.52 270720.18 4475268.37 270705.78 4475283.5 270684.21 4475310.86 270663.49 4475337.36 270648.94 4475363.02 270647.86 4475366.92 270642.19 4475387.46 270639.17 4475402.78 270636.34 4475408.28
</gml:posList>
</gml:LinearRing>
</gml:exterior>
</gml:PolygonPatch>
</gml:patches>
</gml:Surface>
</gml:surfaceMember>
</gml:MultiSurface>
</cp:geometry>
<cp:inspireId xmlns:base="urn:x-inspire:specification:gmlas:BaseTypes:3.2">
<base:Identifier>
<base:localId>37164A00500001</base:localId>
<base:namespace>ES.SDGC.CP</base:namespace>
</base:Identifier>
</cp:inspireId>
<cp:label>00001</cp:label>
<cp:nationalCadastralReference>37164A00500001</cp:nationalCadastralReference>
<cp:referencePoint>
<gml:Point gml:id="ReferencePoint_ES.SDGC.CP.37164A00500001" srsName="urn:ogc:def:crs:EPSG::25830">
<gml:pos>270929.62 4475194.99</gml:pos>
</gml:Point>
</cp:referencePoint>
<cp:validFrom xsi:nil="true" nilReason="other:unpopulated"/>
<cp:validTo xsi:nil="true" nilReason="other:unpopulated"/>
<cp:zoning xlink:href="http://ovc.catastro.meh.es/INSPIRE/wfsCP.aspx?service=wfs&version=2&request=GetFeature&STOREDQUERIE_ID=GetZoning&cod_zona=37164A005&srsname=urn:ogc:def:crs:EPSG::25830"/>
</cp:CadastralParcel>
</gml:featureMember>
</gml:FeatureCollection>`

**Comment by teanocrata** [comment]
Pues en algún momento hemos tenido la distintas subparcelas dibujadas, quizá ese es el tema, que en la consulta para el perfil de la parcela al catastro hay que pedirle también las subparcelas o algo así

**Comment by teanocrata** [comment]
Issue moved to [ilice/OSCWeb #7](https://github.com/ilice/OSCWeb/issues/7) via [**ZenHub**](https://www.zenhub.com/)
