### ISSUE TITLE
Qué implica cada información del catastro

### ISSUE THREAD

**Issue by teanocrata** [ilice/OSCapi#163]
Añadir una descripción algo más específica de lo que es la información catastral que se está mostrando

**Comment by jlafuentegarcia** [comment]
Y eliminar la redirection al catastro para _más información_

**Comment by teanocrata** [comment]
Issue moved to [ilice/OSCWeb #24](https://github.com/ilice/OSCWeb/issues/24) via [**ZenHub**](https://www.zenhub.com/)
